language: node_js
node_js: "lts/dubnium"
cache: npm
script:
  - npm run predeploy
deploy:
  - provider: firebase
    token:
      secure: "hfX3T6VTbFjDyS8CHWMdHEtNimGzfq94Y59vJO4LPegi4VmmagddUxlgQ23Pf2R8XMjEayLymJSNIpIvZPINE3xgCY2ouOEDNa74piJlGDHENKhf/cS5CGzXPuW0k8ghLkgw03/4wZzCCmCiyhSvvFRCc1K/ybX37uxZCsOJjRnkoA+I4OJd6Bvc8APLWb/Znad2F8OYZCMyAV5/sOL6kG0n3VMsp5kzCNIyEK0yEn53/l3Y1EqluQSPJ2+x57AS01z/TtceajTS/WOU8Agc/0kMPrO6tLHGSpItWeDgPYao7cxOAoETVkzG8rDNqQNmqilxq2jFClP+oktjSjKUDWvJNY3SUSd2D3chYBX4SRBjaB5SMdDZ4ve3mwp9Pp+Ox2qq0110tmVMgC8WEAIuqMGmuy5Cx6nShPZzbM08VnbIf4+ywIeqq3FdtbOdDN1Emg82IRBm7nMcbInZOqgByYEfuVnjdh6NaRAbL/BTIWhdC/ztzykFfbOvELMR2NsQ9yn8PBbwKh7Madb/AjC6iBmv8KuQVvhvpmkcwcnwTW4JgJET8dTuYJ6DNW42Ez9c5xqWYl+8pg8beD8vBLnrXP2yQxENRbIr9d5djeIwhf4SN8dxpA9MQ8h0UYYJhFc8JGA3fP0vz1Lbo8hl3xZTxSdNvn9QItvAyMPJWhXHuow="
    message: "Staging deploy from travis."
    project: coreofscience-staging
    skip_cleanup: true
    on:
      branch: master
      repo: coreofscience/coreofscience.org
  - provider: firebase
    token:
      secure: "KTScgbvoz740NGh4yhk4d6crfOYTBgfssPZcNJQvSrgZyUm0ejVsEaEw41nwOyxyICDIPlt1Nci9s3yHA+mlZ09w3KC9GgOkfKvs1xUBeuS0mjkWlI9xu+lwoecEzFmqaPZCNVkC7inETKhQHfyP8vWt3an/yx3+ja0e3Siq752Gkvb64t5s4amAD4C3RIXWup6PR334fcSRC+KV8Hlfyp0Ucs4KBHvXKVllkW+fk3vbPSQ8ZP1d0XCMsaNEGFenza/VDRaT5769VrLiI6v+tZzwsvY2CfIyGIyMqoAwEoayCzl4S87rhhEtj9bJ2CPCzVRTNDH1va+7Nl94/JHWSxDC5+lx7OdMZA8sJ7EVarRZYKaFhyQulp/bN0bKmWXXj872DTdJPoGHP4bBb6pLKzatd8QYfbi1NgTFuR/rwsZEkMCJ6iKsWdh994TVr2Vu340VDzU5GVrVZSgw59HTn4mELVm9Q5ROj1UneJPKQF17+8uv3OgBZW9SCU44AfOCMrBI8ZAMZXDgCWwCVRtTiZV6ND1USnXzXyBz74nKkTSDmJkkYUI83LT1lclimErXDCOOQJK3IyGkfyJlrUZypklLLdvtYagxjcScfgHCWFMme2NBu2K6tzDER8MvPJU46LCdaTTwKKPtAmY7OPqBQGEzS7o+wo6n++1j8TTjwlc="
    message: "Production deploy from travis."
    project: coreofscience
    skip_cleanup: true
    on:
      tags: true
      branch: master
      repo: coreofscience/coreofscience.org