name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: |
          npm ci
          npm run build
        env:
          CI: true
          GATSBY_FIREBASE_API_KEY: ${{ secrets.FIREBASE_WEB_API_KEY_DEV }}
          GATSBY_FIREBASE_AUTH_DOMAIN: "coreofscience-dev.firebaseapp.com"
          GATSBY_FIREBASE_DATABASE_URL: "https://coreofscience-dev.firebaseio.com"
          GATSBY_FIREBASE_PROJECT_ID: "coreofscience-dev"
          GATSBY_FIREBASE_STORAGE_BUCKET: "coreofscience-dev.appspot.com"
          GATSBY_FIREBASE_MESSAGING_SENDER_ID: "421154467745"
          GATSBY_FIREBASE_APP_ID: "1:421154467745:web:d7dd5ed17243869ba765e0"

      - name: Deploy
        run: |
          npm install firebase-tools
          npm run deploy -- --token=${{ secrets.FIREBASE_TOKEN }} -P dev

