name: Deploy to Preview Channel

on:
  pull_request:

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Grab node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/iron"
          cache: "npm"

      - name: Build it
        run: |
          npm ci
          npm run build
        env:
          CI: true
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_WEB_API_KEY_DEV }}
          FIREBASE_AUTH_DOMAIN: "coreofscience-dev.firebaseapp.com"
          FIREBASE_DATABASE_URL: "https://coreofscience-dev.firebaseio.com"
          FIREBASE_PROJECT_ID: "coreofscience-dev"
          FIREBASE_STORAGE_BUCKET: "coreofscience-dev.appspot.com"
          FIREBASE_MESSAGING_SENDER_ID: "421154467745"
          FIREBASE_APP_ID: "1:421154467745:web:d7dd5ed17243869ba765e0"
          FIREBASE_MEASUREMENT_ID: "G-RN1WPXBDB2"

      - name: Ship it
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_DEV_SERVICE_ACCOUNT }}"
          expires: 30d
          projectId: dev
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
