name: Deploy to Preview Channel

on:
  pull_request:
    # Optionally configure to run only for specific files. For example:
    # paths:
    # - "website/**"

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: |
          npm ci
          npm run build
          # Firebase use --alias doesn't work
          cat << EOF > .firebaserc
          {
              "projects": {
                  "default": "coreofscience-dev"
              }
          }
          EOF
          npm run firebase -- target:apply hosting cos coreofscience-dev
        env:
          CI: true
          GATSBY_FIREBASE_API_KEY: ${{ secrets.DEV_API_KEY }}
          GATSBY_FIREBASE_AUTH_DOMAIN: "coreofscience-dev.firebaseapp.com"
          GATSBY_FIREBASE_DATABASE_URL: "https://coreofscience-dev.firebaseio.com"
          GATSBY_FIREBASE_PROJECT_ID: "coreofscience-dev"
          GATSBY_FIREBASE_STORAGE_BUCKET: "coreofscience-dev.appspot.com"
          GATSBY_FIREBASE_MESSAGING_SENDER_ID: "421154467745"
          GATSBY_FIREBASE_APP_ID: "1:421154467745:web:d7dd5ed17243869ba765e0"

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          expires: 30d
          projectId: coreofscience-dev
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
